### ISSUE TITLE
Reshape: invalid input type - expected Tensor or Shape, got Scalar(Int64)

### ISSUE THREAD

**Issue by astnmsn** [tracel-ai/burn-onnx#21]
I have not found any equivalent request

### Feature description

Addition of support for necessary operators to utilize the `vit_b` SAM Model which can be found [here](https://github.com/facebookresearch/segment-anything?tab=readme-ov-file#model-checkpoints): 

[Pth Direct download](https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth)

[ONNX file sam_vit_b.onnx.zip](https://github.com/tracel-ai/burn/files/15168321/sam_vit_b.onnx.zip)

I have inspected the model using Netron and compared the nodes to the support list [here](https://github.com/tracel-ai/burn/blob/main/crates/burn-import/SUPPORTED-ONNX-OPS.md)

Below is the list of operators in the network that are partially or fully missing from the support list
Operator (missing support)

- Mul (Import)
- MatMul (Import)
- Sin (Import)
- Shape (Import)
- Expand (Import)
- Not (Import)
- ReduceMean (Import)
- ConstantOfShape (Full)
- Where (Import)
- Slice (Import)
- OneHot (Import)
- Tile (Import)
- LayerNormalization (Import)
- Gemm (Import)
- ReduceMax (Import)
- Floor (Full)

### Feature motivation

I am currently trying to load and run an onnx model [segment-anything](https://github.com/facebookresearch/segment-anything) inside an image editing app in an effort to provide a masking experience similar to the demo available [here](https://segment-anything.com/demo). I am integrating it into an existing rust codebase using wgpu that compiles to wasm and runs in the browser.

Before I can select `burn` as the ml library to support this workflow, I need to be sure that it supports the operators specified in the model.

**Comment by antimora** [comment]
Thanks for filing this. This is helpful as we prioritize ONNX ops. If you have a direct link to the ONNX file, can you also link this?

**Comment by antimora** [comment]
Updating Expand to Import, since we just added this op. I need to update the docs.

**Comment by antimora** [comment]
Submitted a PR to fix the supported OPs document: https://github.com/tracel-ai/burn/pull/1547

**Comment by astnmsn** [comment]
This is the model [download link](https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth) provided by the SAM repo - I have also added to the original post

**Comment by antimora** [comment]
I think it might be faster to implement the model manually in Burn and load the pth weights file, which we now support.

You can check out an existing model to see how it's done: https://github.com/tracel-ai/models/tree/main/resnet-burn

We also have a YOLOX object detection PR in the works: https://github.com/tracel-ai/models/pull/24

@laggui has written a great tutorial on this subject: https://dev.to/laggui/transitioning-from-pytorch-to-burn-45m

Recently, we made tons of enhancements to the PyTorchFileRecorder: https://discord.com/channels/1038839012602941528/1144670451763785769/1216788417984335872

<img width="703" alt="image" src="https://github.com/tracel-ai/burn-onnx/assets/939125/fb6461e8-f9cf-490c-9f1e-20d1e7dfdb59">



@laggui, @nathanielsimard, @ashdtu, would this be worth implementing ourselves? Should we move this ticket to the models repo?

**Comment by laggui** [comment]
The community is always one step ahead 😄

We've actually discussed adding SAM to our models and this was in the plans following the release.

We still haven't decided whether we want to reimplement it and use the PyTorch file recorder to import the weights or use the ONNX import.

**Comment by antimora** [comment]
@laggui, if we decide to work on this, I am more inclined to adding ONNX OPs. It will be biggest bang for the buck instead of spending time to come up with the model by hand (although I am not sure how complex it is).

**Comment by laggui** [comment]
Btw, not sure if anyone has delved into the SAM code for ONNX export but it doesn't include all the operations to actually run the model for an input image. The encoder part is totally left out of the ONNX export and the exported ONNX model expects image embeddings as input.

In their example they still use their pytorch implementation to provide the embeddings to the ONNX runtime.

So even if we support the missing operations in this issue, SAM support will still not be complete. Is this what you expected @astnmsn?

**Comment by astnmsn** [comment]
@laggui Thanks for asking, and yes that is expected. We plan to run the first half of the model to generate the embeddings on the backend using pytorch. Only the second half, which produces the masks from the embeddings and the cursor/click positions, will be run on the client

**Comment by antimora** [comment]
Regarding Tile Op. We need to rename our current repeat op to repeat_dim and implement a proper repeat for all dimensions at once.

**Comment by antimora** [comment]
Resolving this ticket will resolve https://github.com/tracel-ai/burn/issues/1560 as well.

**Comment by laggui** [comment]
Current state of required ops based on the latest PRs:

| op_type            | Burn | Import |
| :----------------- | :--: | :----: |
| Add                | ✅  | ✅     |
| Cast               | ✅  | ✅     |
| Concat             | ✅  | ✅     |
| Constant           | ✅  | ✅     |
| ConstantOfShape    | ❌  | ❌     |
| Conv               | ✅  | ✅     |
| ConvTranspose      | ✅  | ✅     |
| Cos                | ✅  | ✅     |
| Div                | ✅  | ✅     |
| Equal              | ✅  | ✅     |
| Erf                | ✅  | ✅     |
| Expand             | ✅  | ❌     |
| Floor              | ❌  | ❌     |
| Gather             | ✅  | ✅     |
| Gemm               | ❌  | ❌     |
| LayerNormalization | ✅  | ✔️     |
| MatMul             | ✅  | ✔️     |
| Mul                | ✅  | ✅     |
| Not                | ✅  | ✔️     |
| OneHot             | ✅  | ❌     |
| Pow                | ✅  | ✅     |
| Reciprocal         | ✅  | ✅     |
| ReduceMax          | ✅  | ✔️     |
| ReduceMean         | ✅  | ✔️     |
| Relu               | ✅  | ✅     |
| Reshape            | ✅  | ✅     |
| Resize             | ✅  | ❌     |
| Shape              | ✅  | ✔️     |
| Sin                | ✅  | ✔️     |
| Slice              | ✅  | ❌     |
| Softmax            | ✅  | ✅     |
| Sqrt               | ✅  | ✅     |
| Sub                | ✅  | ✅     |
| Tile               | ✅  | ❌     |
| Transpose          | ✅  | ✅     |
| Unsqueeze          | ✅  | ✅     |
| Where              | ✅  | ✔️     |

**Comment by polarathene** [comment]
> Current state of required ops based on the latest PRs:

I'm not sure if there was a difference intended between ✅ vs ✔ but all ❌ items from that last update are now ✅ at the [`burn-import` ONNX supported ops docs](https://github.com/tracel-ai/burn/blob/main/crates/burn-import/SUPPORTED-ONNX-OPS.md).

Attempting to import now fails here:

```rust
  DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Where"
  DEBUG onnx_ir::from_onnx: renaming node "/Where"
  DEBUG onnx_ir::rank_inference: Inferring rank for node: where1
  DEBUG onnx_ir::node::where_op: Where rank inference for node where1
  ERROR burn_import::logger: PANIC => panicked at /root/.cargo/git/checkouts/burn-6c277d792b0d5d7a/977e712/crates/onnx-ir/src/node/where_op.rs:17:5:
  assertion `left == right` failed: Where x and y have different element types!
    left: Int64
   right: Float32
```

https://github.com/tracel-ai/burn/blob/977e7126e519691cebf8d3111ea653f52c01cbe4/crates/onnx-ir/src/node/where_op.rs#L17-L21

Which is notably further along the import than the current [`0.17.1` release](https://github.com/tracel-ai/burn/releases/tag/v0.17.1) reached:

```rust
  DEBUG onnx_ir::proto_conversion: Converting ONNX node with type "Equal"
  DEBUG onnx_ir::from_onnx: renaming node "/Equal"
  ERROR burn_import::logger: PANIC => panicked at /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/onnx-ir-0.17.1/src/rank_inference.rs:571:13:
  assertion `left != right` failed: Got a rank 0 Tensor, that should have been a Scalar!
    left: 0
   right: 0
```

---

**NOTE:** The `where_op` failure is also hit when trying to import [Depth-Anything-V1](https://github.com/fabio-sim/Depth-Anything-ONNX/releases):

```bash
curl -fsSL -o src/model/dav1.onnx \
  https://github.com/fabio-sim/Depth-Anything-ONNX/releases/download/v1.0.0/depth_anything_vitb14.onnx
```

Depth-Anything-V2 cannot be attempted as it uses operators outside of the standard ONNX domain, so Burn rejects importing.

---

## Reproduction

Provided for convenience if it helps.

### Build

```bash
# Get ONNX model:
mkdir -p /tmp/onnx-example/src/model && cd /tmp/onnx-example
curl -fsSL -o sam.zip https://github.com/tracel-ai/burn/files/15168321/sam_vit_b.onnx.zip
unzip sam.zip sam_vit_b.onnx && rm sam.zip
mv sam_vit_b.onnx src/model/sam.onnx
```

In `/tmp/onnx-example` with source files (in next section), build locally or via container:

```bash
# 1.5GB image size + 300MB fetching crates + 800MB target/ dir:
docker run --rm -it --volume ${PWD}/:/example --workdir /example rust:1.87 cargo build --quiet
```

### Source files

<details>
<summary>Single Dockerfile with everything embedded</summary>

For convenience, single copy/paste to reproduce if you've got Docker:

```bash
# NOTE: Builds an image 1.22GB in size:
docker build --tag localhost/onnx .
docker run --rm -it localhost/onnx bash

# Adds 800MB target dir + 300MB fetched for crates (/root/.cargo):
cargo build
```

```Dockerfile
# Builds a 935MB image (or 1.22GB with optional crates cache):
ARG BASE=crate-cache

FROM fedora:42 AS onnx-model
WORKDIR /models
RUN <<HEREDOC
  dnf install -yq unzip && dnf clean all

  # Add the ONNX model (15.2MB ZIP / 16.5MB ONNX):
  curl -fsSL -o sam.zip https://github.com/tracel-ai/burn/files/15168321/sam_vit_b.onnx.zip
  unzip sam.zip sam_vit_b.onnx && rm sam.zip
  mv sam_vit_b.onnx sam.onnx
HEREDOC

FROM fedora:42 AS builder
# Install Rust (current stable release):
RUN <<HEREDOC
  dnf --setopt=install_weak_deps=0 install -yq rustup gcc && dnf clean all
  rustup-init -y --profile minimal --default-toolchain 1.87
HEREDOC
ENV PATH=/root/.cargo/bin:${PATH}
WORKDIR /example
COPY --from=onnx-model /models/sam.onnx /example/src/model/sam.onnx


# Add sources (embedded inline):
# Simplifies reproduction setup via bundling into the same file vs `COPY . /example`

COPY <<HEREDOC Cargo.toml
[package]
name = "onnx-sam"
version = "0.1.0"
edition = "2024"

[dependencies]

[build-dependencies]
#burn-import = "0.17.1"
burn-import = { git = "https://github.com/tracel-ai/burn.git" }
HEREDOC

COPY <<HEREDOC build.rs
use burn_import::onnx::ModelGen;

fn main() {
  ModelGen::new()
    .input("src/model/sam.onnx")
    .out_dir("model/")
    .run_from_script();
}
HEREDOC

COPY <<HEREDOC src/lib.rs
pub mod model;
pub use model::sam;
HEREDOC

COPY <<HEREDOC src/model/mod.rs
pub mod sam {
  include!(concat!(env!("OUT_DIR"), "/model/sam.rs"));
}
HEREDOC


# Optional: +285MB to include deps pre-fetched
FROM builder AS crate-cache
RUN <<HEREDOC
  # (+130MB: Fetching two git repos burn/cubecl (114MB) + Update crates registry index (16MB))
  cargo generate-lockfile --quiet

  # (+154MB: crates registry src (31MB) + crates registry cache (24MB))
  cargo fetch --quiet --target x86_64-unknown-linux-gnu
HEREDOC

FROM ${BASE}
```

---

</details>

<details>
<summary>Individual files</summary>

**`Dockerfile`:** (_**Optional** - Provides a build environment + ONNX asset_)

```Dockerfile
# Builds a 935MB image

FROM fedora:42 AS builder
RUN <<HEREDOC
  # Install Rust (current stable release):
  dnf --setopt=install_weak_deps=0 install -yq rustup gcc unzip && dnf clean all
  rustup-init -y --profile minimal --default-toolchain 1.87

  # Add the ONNX model (15.2MB ZIP / 16.5MB ONNX):
  curl -fsSL -o sam.zip https://github.com/tracel-ai/burn/files/15168321/sam_vit_b.onnx.zip
  unzip sam.zip sam_vit_b.onnx && rm sam.zip
  mkdir -p /example/src/model
  mv sam_vit_b.onnx /example/src/model/sam.onnx
HEREDOC

ENV PATH=/root/.cargo/bin:${PATH}
WORKDIR /example
# Add sources:
COPY . /example
```

**`Cargo.toml`:**

```toml
[package]
name = "onnx-sam"
version = "0.1.0"
edition = "2024"

[dependencies]

[build-dependencies]
#burn-import = "0.17.1"
burn-import = { git = "https://github.com/tracel-ai/burn.git" }
```

**`build.rs`:**

```rust
use burn_import::onnx::ModelGen;

fn main() {
  ModelGen::new()
    .input("src/model/sam.onnx")
    .out_dir("model/")
    .run_from_script();
}
```

**`src/lib.rs`:**

```rust
pub mod model;
pub use model::sam;
```

**`src/model/mod.rs`:**

```rust
pub mod sam {
  include!(concat!(env!("OUT_DIR"), "/model/sam.rs"));
}
```

</details>

**Comment by antimora** [comment]
@polarathene thanks created an issue: https://github.com/tracel-ai/burn/issues/3264

**Comment by antimora** [comment]
Currently sam_vit_b_opset16.onnx is failing on

```
ERROR burn_import::logger: PANIC => panicked at crates/onnx-ir/src/node/reshape.rs:55:14:
Reshape: invalid input type - expected Tensor or Shape, got Scalar(Int64)

thread 'main' panicked at crates/onnx-ir/src/node/reshape.rs:55:14:
Reshape: invalid input type - expected Tensor or Shape, got Scalar(Int64)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by antimora** [comment]
Narrowed the scope down. Will track model level issues here: https://github.com/tracel-ai/burn-onnx/issues/18

**Comment by antimora** [comment]
Can confirm this is still an issue:

```
}), value: None, passed: false } for const
DEBUG onnx_ir::from_onnx: Input constant49_out1 matched constant node constant49
DEBUG onnx_ir::from_onnx: Lifted and removed constant node constant49 for reshape2 (single use)
DEBUG onnx_ir::from_onnx: Skipping constant creation for reshape2 input 1 (will be lifted)
DEBUG onnx_ir::rank_inference: Inferring rank for node: reshape2
ERROR burn_import::logger: PANIC => panicked at crates/onnx-ir/src/node/reshape.rs:55:14:
Reshape: invalid input type - expected Tensor or Shape, got Scalar(Int64)

thread 'main' panicked at crates/onnx-ir/src/node/reshape.rs:55:14:
Reshape: invalid input type - expected Tensor or Shape, got Scalar(Int64)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[burn-import]%
```

**Comment by HiDolen** [comment]
Encountered the same issue. It would be great if it could be solved!

**Comment by antimora** [comment]
@HiDolen 

> Encountered the same issue. It would be great if it could be solved!

We merged a fix for Reshape of scalar today: https://github.com/tracel-ai/burn/pull/4119

Can you check if this works for you?

Also there is a new PR to optimize no-op reshape scalars: https://github.com/tracel-ai/burn/pull/4146 This will help with unnecessary Scalar to Tensor conversion.

**Comment by HiDolen** [comment]
> We merged a fix for Reshape of scalar today: [#4119](https://github.com/tracel-ai/burn/pull/4119)
> 
> Can you check if this works for you?

Thank you for such a prompt reply!

I just pulled the latest code from the main branch using `burn = { git = "https://github.com/tracel-ai/burn.git ", branch = "main", features = ["ndarray"] }`, but I’m still getting exactly the same error.

My ONNX model is unusually large for some reason, and I’m currently looking into the cause. Once I figure it out, I might be able to upload an example model.

**Comment by antimora** [comment]
> > We merged a fix for Reshape of scalar today: [#4119](https://github.com/tracel-ai/burn/pull/4119)
> > Can you check if this works for you?
> 
> Thank you for such a prompt reply!
> 
> I just pulled the latest code from the main branch using `burn = { git = "https://github.com/tracel-ai/burn.git ", branch = "main", features = ["ndarray"] }`, but I’m still getting exactly the same error.
> 
> My ONNX model is unusually large for some reason, and I’m currently looking into the cause. Once I figure it out, I might be able to upload an example model.

Oh okay. We can take a look if you small example.

**Comment by HiDolen** [comment]
You should be able to trigger the error just by loading it directly in `build.rs`. And I figured out it's the STFT operation that's causing the ONNX model size to balloon.

```rust
use burn_import::onnx::ModelGen;

fn main() {
    ModelGen::new()
        .input("bsroformer_1.2M_test_withoutSTFT.onnx")
        .out_dir("model/")
        .run_from_script();
}
```

[bsroformer_1.2M_test_withoutSTFT.zip](https://github.com/user-attachments/files/24067702/bsroformer_1.2M_test_withoutSTFT.zip)

**Comment by antimora** [comment]
> You should be able to trigger the error just by loading it directly in `build.rs`. And I figured out it's the STFT operation that's causing the ONNX model size to balloon.
> 
> use burn_import::onnx::ModelGen;
> 
> fn main() {
>     ModelGen::new()
>         .input("bsroformer_1.2M_test_withoutSTFT.onnx")
>         .out_dir("model/")
>         .run_from_script();
> }
> [bsroformer_1.2M_test_withoutSTFT.zip](https://github.com/user-attachments/files/24067702/bsroformer_1.2M_test_withoutSTFT.zip)

Thanks for report. Downloaded and viewed using Netron. I haven't debugged yet but I can see that `ScatterND` Op is used which isn't supported yet.

**Comment by HiDolen** [comment]
> I haven't debugged yet but I can see that `ScatterND` Op is used which isn't supported yet.

Thanks for tracking that down! I'm still not very familiar with it. I'll try lowering the `opset_version` to see if it helps.

**Comment by akshitgaur2005** [comment]
I was having this problem for SAM2, but upgrading to the git branch changed the error to this-

```
  DEBUG onnx_ir::phases::node_conversion: Preserving outer-scope value_store for 'constant141_out1' (Constant)
   WARN onnx_ir::graph_state: Input  not found, should only happen when peeking
   WARN onnx_ir::graph_state: Input  not found, should only happen when peeking
  DEBUG onnx_ir::pipeline:  PHASE 3: Type Inference 
  ERROR burn_import::logger: PANIC => panicked at /home/akshit/.cargo/git/checkouts/burn-6c277d792b0d5d7a/f1e90cf/crates/burn-import/src/onnx/model_gen.rs:296:33:
  Failed to parse ONNX file 'src/models/2.1/tiny/decoder_opset16.onnx': Type inference failed: TypeMismatch { expected: "Tensor", actual: "Shape(1)" }

  --- stderr

  thread 'main' (70) panicked at /home/akshit/.cargo/git/checkouts/burn-6c277d792b0d5d7a/f1e90cf/crates/burn-import/src/onnx/model_gen.rs:296:33:
  Failed to parse ONNX file 'src/models/2.1/tiny/decoder_opset16.onnx': Type inference failed: TypeMismatch { expected: "Tensor", actual: "Shape(1)" }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

The model I am trying out is [sam2.1_hiera_tiny_decoder.onnx](https://huggingface.co/mabote-itumeleng/ONNX-SAM2-Segment-Anything/blob/main/sam2.1_hiera_tiny_decoder.onnx)

**Comment by antimora** [comment]
This ticket seems to be overloaded with many issues; Lets open specific problem; closing it since they have been lots of improvements and fixes since this had been filed.
